services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: doctor_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shroyash
    ports:
      - "5432:5432"

  eureka-server:
    build: ./discovery-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    ports:
      - "8008:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doctor_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  ai-diagnostics-service:
    build: ./ai-diagnostics-service
    container_name: ai-diagnostics-service
    ports:
      - "8000:8000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8001:8000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "8002:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appointment_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  batch-service:
    build: ./batch-service
    container_name: batch-service
    ports:
      - "8004:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/batch_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8005:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billing_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8010:8000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8011:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8012:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/search_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
