services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shroyash
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    restart: unless-stopped

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    ports:
      - "8008:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doctor_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  ai-diagnostics-service:
    build: ./ai-diagnostics-service
    container_name: ai-diagnostics-service
    ports:
      - "9091:8000"
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8001:8000"
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    restart: unless-stopped

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "8002:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appointment_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  batch-service:
    build: ./batch-service
    container_name: batch-service
    ports:
      - "8004:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/batch_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8005:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billing_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8010:8000"
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    restart: unless-stopped

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8011:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8012:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/search_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shroyash
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped
