server:
  port: 8001   # API Gateway exposed port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Enable automatic routes from Eureka
          lower-case-service-id: true
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctor/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: batch-service
          uri: lb://batch-service
          predicates:
            - Path=/batch/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: ai-diagnostics-service
          uri: lb://ai-diagnostics-service
          predicates:
            - Path=/ai/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
