server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctors/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
