server:
  port: 8001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatically routes based on Eureka service IDs
          lower-case-service-id: true  # Convert service IDs to lowercase in URLs
      routes:
        # AI Diagnostics Service
        - id: ai-diagnostics
          uri: lb://AI-DIAGNOSTICS-SERVICE
          predicates:
            - Path=/ai-diagnostics/**
          filters:
            - StripPrefix=1

        # Authentication Service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # User/Patient Service
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=1

        # Doctor Service
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**
          filters:
            - StripPrefix=1

        # Appointment Service
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**
          filters:
            - StripPrefix=1

        # Billing Service
        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing/**
          filters:
            - StripPrefix=1

        # Notification Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

        # Search Service
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1

        # Batch Service
        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch/**
          filters:
            - StripPrefix=1

      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allow-credentials: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: api-gateway

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"